### ISSUE TITLE
Update UI in Event listing page

### ISSUE THREAD

**Issue by prelangi** [WomenWhoCode/WomenWhoCodeSwift#101]

**Comment by prelangi** [comment]
Let me know if you gals like this UI or want it in a different way. 
I will work on the auto layout depending on your input. 

![image](https://cloud.githubusercontent.com/assets/3711263/13902130/52e2b956-edf9-11e5-8b0b-d23fd2e67b77.png)

**Comment by vnu** [comment]
@prelangi The date should be left aligned, RSVP should be right aligned.

**Comment by vnu** [comment]
Also the color. Dark grey and light grey

**Comment by prelangi** [comment]
Thanks for the feedback @vnu 
How does this look ? 

![image](https://cloud.githubusercontent.com/assets/3711263/13906501/cabe67f4-ee94-11e5-8a9f-aa25d53ec563.png)

@mahagovind , @vnu : Please comment and I can start working on this.

**Comment by vnu** [comment]
I'm going to add a mockup with some comments

**Comment by vnu** [comment]
EventCell Feedback:
![image](https://cloud.githubusercontent.com/assets/1395635/13906790/a048978a-ee9c-11e5-963e-f9b5e07bb1d2.png)

**Comment by prelangi** [comment]
![image](https://cloud.githubusercontent.com/assets/3711263/13907460/e4cd8ab4-eeab-11e5-937d-a037efcc0756.png)

@mahagovind @vnu : Here's the cell with your suggestions
@vnu : We cannot make the button's trailing edge with the arrow since the button is separate from the cell's content view. See below: 
![image](https://cloud.githubusercontent.com/assets/3711263/13907471/1f9ee3d6-eeac-11e5-90c2-e60e53d5310f.png)

**Comment by vnu** [comment]
Aligning with the text works as well. So I'm good with your final push
