### ISSUE TITLE
Group Project Submission Wk1

### ISSUE THREAD

**Issue by vnu** [WomenWhoCode/WomenWhoCodeSwift#28]
### Backend
We are integrating with Parse as backend.

### Tab 1: Events 
List of events that members can attend and its detail page

### Tab2: Connect
Search for other members

### Tab3: Profile
User profile with settings.

### Gif
![wwc_wk1](https://cloud.githubusercontent.com/assets/1395635/13588434/7e4af49c-e484-11e5-98be-983de0a6c465.gif)

**Comment by mahagovind** [comment]
Login / Sign Up GIF 
![wwc_login_video_walkthrough](https://cloud.githubusercontent.com/assets/16600833/13590218/eaf243d0-e492-11e5-96ae-9319e4e0fbb9.gif)
