### ISSUE TITLE
Fix Profile view for Autolayout Constraints

### ISSUE THREAD

**Issue by nikitapahadia** [WomenWhoCode/WomenWhoCodeSwift#29]

**Comment by prelangi** [comment]
@nikitapahadia : This is part of our CodePath iOS project and we still haven't open sourced the app yet. This is our first version and we will be improving the app over the coming few weeks.

**Comment by nikitapahadia** [comment]
@prelangi Thanks for letting me know. I would like to contribute to the app, I have a good experience in iOS. I was trying to get started with UI stuff. If it is fine, can you help me out with what part of the app I can work on? Thanks

**Comment by vnu** [comment]
@nikitapahadia We appreciate your interest. Keep watching the repository and we'll update the README. Probably in few weeks. Thanks.
