### ISSUE TITLE
Event List Page Skeleton

### ISSUE THREAD

**Issue by vnu** [WomenWhoCode/WomenWhoCodeSwift#3]
Create a list of events

**Comment by prelangi** [comment]
How does this listing page look ? 
I am thinking event description will come up in the details page. Please comment and let me know. 

<img width="269" alt="screen shot 2016-03-02 at 6 23 12 pm" src="https://cloud.githubusercontent.com/assets/3711263/13482814/2f7e827c-e0a4-11e5-9dff-116fd0cfa671.png">
