### ISSUE TITLE
Sprint -3 Tasks 

### ISSUE THREAD

**Issue by mahagovind** [WomenWhoCode/WomenWhoCodeSwift#93]
1.Timeline 
Required 

- [ ] a) Change color of Post Description to white and let the header alone be colored 
- [ ] b)Get Topic pictures from the api 
- [ ] c)Add applaud count and applaud count icon 
- [ ] d)Add constraints 

Optional 

- [ ] a)Clicking on a post takes the user to details page 
- [ ] b)Add comments about events to the timeline  

2.Events 
Required
- [ ] Update UI as discussed 
- [x] Make sure events are filtered based on the choices 
- [x] Sort filters alphabetically 

3.EventDetails
Required 

- [ ] a)Update UI 
- [ ] b)Fetch correct details from meetup API
- [ ] c)Add constraints 

Optional

- [ ] a)Integrate comments about events 
- [ ] b)Clicking on attendees takes the user to their profile 
- [ ] c)Connect to Meetup (WebView)

4.User Search 
Required 

- [ ] a)Clean up parse table to remove redundant users
- [ ] b)Fetch correct profile pictures 
- [x] c)UI changes 
- [x] d)Add constraints 

5.Topics 

- [ ] a)Required
- [ ] b)Topic Details
- [ ] c)Add Profile/Topic model
- [ ] d)Add constraints 

6.Profile 
Required 

- [ ] a)Add follow button
- [ ] b)Change segmented control to match colors
- [ ] c)Settings page 
- [ ] d)Add constraints 
- [ ] e) Fix Topics UI
- [ ] f) Fix Events UI

**Comment by vnu** [comment]
Use 14 as the font size or at the max 15.

**Comment by prelangi** [comment]
Completed required tasks in Timeline

1.Timeline 
Required: 
- [X] Change color of Post Description to white and let the header alone be colored 
- [X] Get Topic pictures from the api 
- [X] Add applaud count and applaud count icon 
- [X] Add constraints 

Optional Tasks:
- [ ] Clicking on a post takes the user to details page 
- [ ] Add comments about events to the timeline
